name: test_env_xgcm
channels:
  # Get the latest numba from numba/label/dev
  - numba/label/dev
  - conda-forge
dependencies:
  - python
  - numpy
  - numba
  - pytest
  - future
  - pip
  - black
  - pip:
    - docrep<=0.2.7
    - codecov
    - pytest-cov
    - pytest-xdist
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
    - toolz